#!/usr/bin/env bash

if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  # Disables strict host key checking and specifies SSH private key
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
